# Generated by Django 4.0.4 on 2022-11-10 03:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=50)),
                ('repeticiones', models.CharField(max_length=50)),
                ('descanso', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCargo', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreClase', models.CharField(max_length=50)),
                ('cantidadAlumnos', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Clases Grupales',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('foto', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('numeroDocumento', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('numeroTelefono', models.IntegerField()),
                ('creado', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCodigoCupon', models.CharField(max_length=50)),
                ('fechaInicioCupon', models.DateTimeField()),
                ('fechaExpiracionCupon', models.DateTimeField()),
                ('descuentoCupon', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicial', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('codigoCupon', models.CharField(max_length=50)),
                ('cantidadDescuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldobruto', models.IntegerField()),
                ('deduccion', models.IntegerField()),
                ('bonificaciones', models.IntegerField()),
                ('detalles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='Ejercicios')),
                ('maquina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('genero', models.IntegerField()),
                ('documento', models.CharField(max_length=50)),
                ('numerodocumento', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LogCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LogEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicialPago', models.DateTimeField()),
                ('fechaFinalPago', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipoRutina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSalon', models.CharField(max_length=50)),
                ('cantidadAlumnos', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGeneroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGenero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMembresia', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSangreCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSangre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistoricoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicial', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('precio', models.IntegerField()),
                ('nombreMembresias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipomembresia')),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('tipoMembresia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipomembresia')),
            ],
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaMedida', models.DateTimeField()),
                ('fotoFrontal', models.CharField(max_length=50)),
                ('fotoLateral', models.CharField(max_length=50)),
                ('peso', models.IntegerField()),
                ('indiceMasaMuscular', models.DecimalField(decimal_places=3, max_digits=10)),
                ('indiceGrasaMuscular', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pecho', models.DecimalField(decimal_places=3, max_digits=10)),
                ('espalda', models.DecimalField(decimal_places=3, max_digits=10)),
                ('brazo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('antebrazo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cadera', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cintura', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pierna', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pantorrilla', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
            ],
            options={
                'verbose_name_plural': 'Medidas',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='TipoDocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipodocumentocliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipogenerocliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoSangre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tiposangrecliente'),
        ),
    ]
