# Generated by Django 4.0.4 on 2022-11-30 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='descripcion',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='cai',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='codigoSucursal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='fechaEmision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='fechaVencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='rangoFinal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='rangoInicial',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='ultimaFactura',
            field=models.IntegerField(),
        ),
    ]
