# Generated by Django 4.1.3 on 2022-11-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('foto', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('documento', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('numeroTelefono', models.IntegerField()),
                ('genero', models.IntegerField()),
                ('grupoSanguineo', models.IntegerField()),
            ],
        ),
    ]
