# Generated by Django 4.1.3 on 2022-11-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaMedida', models.DateTimeField()),
                ('fotoFrontal', models.CharField(max_length=50)),
                ('fotoLateral', models.CharField(max_length=50)),
                ('peso', models.IntegerField()),
                ('indiceMasaMuscular', models.DecimalField(decimal_places=3, max_digits=10)),
                ('indiceGrasaMuscular', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pecho', models.DecimalField(decimal_places=3, max_digits=10)),
                ('espalda', models.DecimalField(decimal_places=3, max_digits=10)),
                ('brazo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('antebrazo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cadera', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cintura', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pierna', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pantorrilla', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGeneroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGenero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSangreCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSangre', models.CharField(max_length=50)),
            ],
        ),
    ]
