# Generated by Django 4.0.4 on 2022-12-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comida_descripcion_alter_parametrosfactura_cai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Membresia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dieta',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='medidas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rutina',
        ),
        migrations.AddField(
            model_name='descuento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='medidas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
    ]
