# Generated by Django 4.1.3 on 2022-11-03 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medidas_tipodocumentocliente_tipogenerocliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
