# Generated by Django 4.0.4 on 2022-11-12 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_empleadocargo_cargo_empleadocargo_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionclase',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado'),
        ),
        migrations.AddField(
            model_name='asignacionclase',
            name='nombreClase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clasegrupal'),
        ),
        migrations.AddField(
            model_name='asignacionclase',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.salon'),
        ),
    ]
