# Generated by Django 4.0.4 on 2022-12-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cliente_membresia_remove_cliente_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionclase',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
    ]
