# Generated by Django 4.1.3 on 2022-11-04 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cliente_creado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCargo', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreClase', models.CharField(max_length=50)),
                ('cantidadAlumnos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCodigoCupon', models.CharField(max_length=50)),
                ('fechaInicioCupon', models.DateTimeField()),
                ('fechaExpiracionCupon', models.DateTimeField()),
                ('descuentoCupon', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicial', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('codigoCupon', models.CharField(max_length=50)),
                ('cantidadDescuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldobruto', models.IntegerField()),
                ('deduccion', models.IntegerField()),
                ('bonificaciones', models.IntegerField()),
                ('idDeduccion', models.IntegerField()),
                ('idSueldo', models.IntegerField()),
                ('detalles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('genero', models.IntegerField()),
                ('documento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LogCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LogEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicialPago', models.DateTimeField()),
                ('fechaFinalPago', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistoricoMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicial', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSalon', models.CharField(max_length=50)),
                ('cantidadAlumnos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupoSanguineo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoSangre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tiposangrecliente'),
        ),
        migrations.AlterField(
            model_name='tipomembresia',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
