# Generated by Django 4.0.4 on 2022-11-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_asignacionclase_empleado_asignacionclase_nombreclase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionrutina',
            options={'verbose_name_plural': 'Asignaciones Rutinas'},
        ),
        migrations.AddField(
            model_name='asignaciondieta',
            name='comida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.comida'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='asignacionDieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.asignaciondieta'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='AsignacionRutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.asignacionrutina'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente'),
        ),
        migrations.CreateModel(
            name='MusculoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ejercicio')),
                ('musculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.musculo')),
            ],
        ),
        migrations.AddField(
            model_name='asignacionrutina',
            name='MusculoEjercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.musculoejercicio'),
        ),
    ]
