# Generated by Django 4.0.4 on 2022-11-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_asignacionrutina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleado'),
        ),
    ]
