# Generated by Django 4.0.4 on 2022-11-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_asignacionclase_cargo_clasegrupal_cupones_descuento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupones',
            new_name='Cupon',
        ),
        migrations.AlterModelOptions(
            name='clasegrupal',
            options={'verbose_name_plural': 'Clases Grupales'},
        ),
        migrations.AlterModelOptions(
            name='cupon',
            options={'verbose_name_plural': 'Cupones'},
        ),
        migrations.AlterModelOptions(
            name='medidas',
            options={'verbose_name_plural': 'Medidas'},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name_plural': 'Salones'},
        ),
        migrations.RenameField(
            model_name='tipomembresia',
            old_name='nombre',
            new_name='nombreMembresia',
        ),
        migrations.RemoveField(
            model_name='detalleplanilla',
            name='idDeduccion',
        ),
        migrations.RemoveField(
            model_name='detalleplanilla',
            name='idSueldo',
        ),
    ]
