# Generated by Django 4.0.4 on 2022-11-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_categoria_producto_descuento_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='Membresia',
            new_name='membresia',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='DetalleFactura',
            new_name='detalleFactura',
        ),
    ]
