# Generated by Django 4.0.4 on 2022-11-20 06:23

import api.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cliente_activo_cliente_bloqueado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='asignacionclase',
            name='fecha',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='asignaciondieta',
            name='fecha',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='asignacionrutina',
            name='capacidad',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='asignacionrutina',
            name='descanso',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='asignacionrutina',
            name='repeticiones',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='asignacionrutina',
            name='series',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombreCargo',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='clasegrupal',
            name='nombreClase',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='creado',
            field=models.DateField(default=django.utils.timezone.now, validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(validators=[api.validators.validate_fecha, api.validators.validate_mayordedieciochoaños]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='comida',
            name='descripcion',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='comida',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='NombreCodigoCupon',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='codigoCupon',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='detalleplanilla',
            name='detalles',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fechaDevolucion',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='nombreProducto',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='razonDevolucion',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='documentoempleado',
            name='nombreDocumento',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='maquina',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='clave',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaNacimiento',
            field=models.DateField(validators=[api.validators.validate_fecha, api.validators.validate_mayordeveintiuno]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='fechaFinal',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='fechaInicial',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='logcliente',
            name='accion',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='logcliente',
            name='informacion',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='logempleado',
            name='accion',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='logempleado',
            name='informacion',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='loginadministrador',
            name='accion',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='loginadministrador',
            name='fecha',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='loginadministrador',
            name='informacion',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='fotoFrontal',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='fotoLateral',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='musculo',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='orden',
            name='direccionEnvio',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fechaEnvio',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fechaOrden',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fechaRequerida',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='cai',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='fechaEmision',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='parametrosfactura',
            name='fechaVencimiento',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='preciohistoricoproducto',
            name='fechaFinal',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='preciohistoricoproducto',
            name='fechaInicial',
            field=models.DateField(validators=[api.validators.validate_fecha]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='tipoRutina',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='salon',
            name='nombreSalon',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='tipodocumentocliente',
            name='nombreDocumento',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='tipogenero',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='tipogenerocliente',
            name='nombreGenero',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='tipomembresia',
            name='descripcion',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='tipomembresia',
            name='nombreMembresia',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='tiposangrecliente',
            name='nombreSangre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), api.validators.validate_nombre]),
        ),
    ]
