# Generated by Django 4.0.4 on 2022-11-20 07:01

import api.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_administrador_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='creado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numeroTelefono',
            field=models.CharField(max_length=8, validators=[api.validators.validate_numerotelefono, django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=8, validators=[api.validators.validate_numerotelefono, django.core.validators.MinLengthValidator(8)]),
        ),
    ]
