# Generated by Django 4.0.4 on 2022-11-25 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_empleadocargo_empleado_empleado_empleadocargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='membresia',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='dieta',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='preciohistoricoproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='empleado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.membresia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.descuento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dieta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='medidas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medidas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rutina'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.planilla'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.descuento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioHistoricoProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.preciohistoricoproducto'),
        ),
    ]
