# Generated by Django 4.0.4 on 2022-11-28 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_asignacionrutina_capacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='creado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empleado',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.IntegerField(default=0),
        ),
    ]
