# Generated by Django 4.0.4 on 2022-11-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cliente_intentos_alter_asignacionrutina_capacidad_and_more'),
        ('api', '0018_empleado_activo_empleado_bloqueado_empleado_creado_and_more'),
    ]

    operations = [
    ]
